sdk:
  - pubspec
  - stable
  # - dev

stages:
  - analyze:
      - format:
        sdk:
          - pubspec
      - analyze: --fatal-infos .
  - build:
      - command: dart run build_runner build --delete-conflicting-outputs --fail-on-severe
  - unit_test:
      - command: dart run build_runner test --delete-conflicting-outputs --fail-on-severe -- -P ci
