name: angular_ast
repository: https://github.com/angulardart/angular
description: Parser and utilities for AngularDart templates
version: 2.1.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  analyzer: ^4.0.0
  charcode: ^1.1.0
  collection: ^1.14.5
  meta: ^1.1.4
  source_span: ^1.4.0
  string_scanner: ^1.0.1

dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.0.0
  path: ^1.6.1
  lints: ^2.0.0
  test: ^1.3.0
