name: ngdart
version: 7.1.1
description: >-
  Fast and productive web framework by Google.
  Separate, but similar to the JavaScript framework with a similar name.
repository: https://github.com/angulardart-community/angular
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  build: ^2.3.1
  built_collection: ^5.1.1
  built_value: ^8.4.2
  collection: ^1.17.0
  intl: ^0.18.0
  js: ^0.6.5
  meta: ^1.8.0
  ngast: ^2.1.4
  ngcompiler: ^2.1.4-dev
  stream_transform: ^2.1.0

dev_dependencies:
  lints: ^2.0.1
