sdk:
#- 2.12.0
- dev

stages:
- analyze:
  - group:
    - analyze #: --fatal-infos
    sdk: dev
#  - group:
#    - analyze
#    sdk: 2.12.0
- build:
  - command: dart pub run build_runner build --fail-on-severe
