name: examples_hello_world

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # No strict dependencies, we always use dependency_overrides.
  ngdart: any

dev_dependencies:
  build_runner: ^2.4.6
  build_web_compilers: ^4.0.4
  lints: ^3.0.0
