targets:
  $default:
    builders:
      build_web_compilers:entrypoint:
        generate_for:
          - test/**.dart
        options:
          dart2js_args:
            - -O1
            - --no-source-maps
