name: Bug Report
description: Report a bug in the AngularDart Framework
labels: ["bug"]

body:
  - type: markdown
    id: welcome
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!

  - type: dropdown
    id: affected-packages
    attributes:
      label: Which ng* package(s) are the source of the bug?
      options:
        - ngast
        - ngcompiler
        - ngdart
        - ngforms
        - ngrouter
        - ngtest
        - Don't known / other
      multiple: true
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Which operating system(s) does this bug appear on?
      options:
        - Windows
        - MacOS
        - Linux
      multiple: true

  - type: input
    id: browser
    attributes:
      label: Which browser(s) does this bug appear on?
      description: |
        Acceptable values should be in the form of "Chrome 100.3.4.2397", "Firefox 99.6.114514". If it is not related to the browser, type "N/A".
    validations:
      required: true

  - type: dropdown
    id: is-regression
    attributes:
      label: Is this a regression?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe in  what the bug is, exactly how, what and when it happens. In particular specifying what you thought should happen and what did happen, and how they differ, in detail. Unless the bug is abundantly clear by the "one liner" (rarely is), this is mandatory. Try to be concise but it's better to write too much than too little.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Please provide the steps to reproduce the bug
      description: |
        A [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), i.e., code that allows us to replicate the bug. This is **mandatory**. It can be one line, if it already is enough to reproduce (rarely is), or a bigger example with all your relevant code. You **must** use code blocks to put your code in. Don't send your whole project repo, please read the article linked and extract a **minimal** example, but feel free to link a newly created sample repo reproducing the issue instead of pasting code if necessary (rarely is). If you do link a repo, you must put in at least a little bit of the relevant code and where to find it in the repo.
      placeholder: |
        Please include the full commands invoked.

  - type: textarea
    id: exception-or-error
    attributes:
      label: Please provide the exception or error you saw
      render: true

  - type: textarea
    id: environment
    attributes:
      label: Please provide the dependency environment you discovered this bug in (run `dart pub deps -s compact`)
      render: true
      placeholder: |
        Dart SDK 2.17.5
        Flutter SDK 3.0.3
        myproject 1.0.1
        
        dependencies:
        - analyzer 4.1.0 [_fe_analyzer_shared collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
        - build 2.3.0 [analyzer async convert crypto glob logging meta path]
        - build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
        - built_collection 5.1.1
        - built_value 8.3.3 [built_collection collection fixnum meta]
        ...
        
        dev dependencies:
        - build_runner 2.1.11 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
        ... 

        transitive dependencies:
        - _fe_analyzer_shared 40.0.0 [meta]
        - args 2.3.1
        - async 2.9.0 [collection meta]
        ...
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Anything else?
