name: nganalyzer
description: Analyzer plugin for AngularDart.
version: 8.0.0-dev.1
repository: https://github.com/angulardart-community/angular

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  analyzer: ^5.13.0
  analyzer_plugin: ^0.11.2
  ngast: ^3.0.0-dev.0

dev_dependencies:
  build_runner: ^2.3.3
  build_version: ^2.1.1
  lints: ^2.0.0
  test: ^1.21.0
