sdk:
  - dev
  - stable
  - 2.17.0

stages:
  - analyze:
      - format
      - analyze: --fatal-infos
  - build:
      - command: dart run build_runner build --fail-on-severe
  - unit_test:
      - command: dart run build_runner test --fail-on-severe -- -P ci
