sdk:
  - pubspec
  - dev

stages:
  - analyze:
      - format:
        sdk:
          - pubspec
      - analyze: --fatal-infos .
  - unit_test:
      - test: -P ci

cache:
  directories:
    - .dart_tool/build
