name: ngcompiler
repository: https://github.com/angulardart-community/angular
description: |
  The AngularDart compiler. It compiles your component files written in Dart
  into templates so that you don't have to worry about all the complicated
  hassle.
version: 2.1.4-dev

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  # ngdart doesn't need a tight version constraint, since it is ngdart that
  # depends on ngcompiler.
  ngdart: ^7.1.1
  # Allowing a tiny bit of wiggle here to allow publishing minor updates
  ngast: ^2.1.4

  analyzer: ^4.2.0
  args: ^2.0.0
  build: ^2.0.0
  build_test: ^2.0.0
  code_builder: ^4.3.0
  collection: ^1.15.0
  csslib: ^0.17.0
  dart_style: ^2.0.0
  logging: ^1.0.0
  meta: ^1.1.4
  package_config: ^2.0.0
  path: ^1.6.1
  source_gen: ^1.0.0
  source_span: ^1.4.0
  stack_trace: ^1.9.1

dev_dependencies:
  # This is here in order for it to be resolvable by the analyzer.
  build_runner: ^2.0.0
  mockito: ^5.0.7
  lints: ^2.0.0
  test: ^1.3.0
