include: ../analysis_options.yaml

analyzer:
  errors:
    implementation_imports: ignore

    # False positives related to missing .template.dart files
    # Comment this rules while developing.
    argument_type_not_assignable: ignore
    invalid_assignment: ignore
    non_bool_condition: ignore
    return_of_invalid_type: ignore
