sdk:
  - pubspec
  - stable
  # - dev

stages:
  - build:
      - command: dart run build_runner build --delete-conflicting-outputs --fail-on-severe
  - unit_test:
      - command: dart test -P vm
      - command: dart run build_runner test --delete-conflicting-outputs --fail-on-severe -- -P browser
