sdk:
- dev

stages:
- build:
  - command: dart pub run build_runner build --fail-on-severe
- unit_test:
  - command: dart pub run test -P vm
  - command: dart pub run build_runner test --fail-on-severe -- -P browser
