name: _tests
description: Tests for AngularDart.
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  build_resolvers: ^2.1.0
  build_test: ^2.1.6
  collection: ^1.17.0
  ngdart: ^7.1.1
  ngtest: ^4.1.1
  test: ^1.22.2

dev_dependencies:
  analyzer: ^5.4.0
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
  lints: ^2.0.1
  meta: ^1.8.0
  mockito: ^5.3.2
  package_config: ^2.1.0
  source_span: ^1.9.1
  term_glyph: ^1.2.1

dependency_overrides:
  ngast:
    path: ../ngast
  ngcompiler:
    path: ../ngcompiler
  ngdart:
    path: ../ngdart
  ngforms:
    path: ../ngforms
  ngtest:
    path: ../ngtest
