name: _tests
description: Tests for AngularDart.
environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  # No strict dependencies, we always use dependency_overrides.
  ngdart:
  ngtest:

  # Actual valid dependencies required.
  build_resolvers: ^2.0.0
  collection: ^1.15.0
  meta: ^1.3.0
  test: ^1.16.0

dev_dependencies:
  # No strict dependencies, we always use dependency_overrides.
  ngforms:

  # Actual valid dependencies required.
  analyzer: ^4.0.0
  build_runner: ^2.0.0
  build_test: ^2.0.0
  build_web_compilers: #^2.0.0
  mockito: ^5.0.0
  package_config: ^2.0.0
  lints: ^2.0.0
  source_span: ^1.8.0
  term_glyph: ^1.2.0

# DO NOT REMOVE. We don't publish this package, it is just for testing.
dependency_overrides:
  ngdart:
    path: ../ngdart
  ngast:
    path: ../ngast
  ngcompiler:
    path: ../ngcompiler
  ngforms:
    path: ../ngforms
  ngrouter:
    path: ../ngrouter
  ngtest:
    path: ../ngtest
  analyzer: ^4.0.0
