name: ngtest
description: >
  Testing runner and library for AngularDart.
  This package is necessary to write component tests for AngularDart components.
version: 4.1.1
repository: https://github.com/angulardart-community/angular

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  collection: ^1.17.0
  meta: ^1.8.0
  ngdart: ^7.1.1

dev_dependencies:
  build_runner: ^2.3.3
  build_test: ^2.1.6
  build_web_compilers: ^3.2.7
  lints: ^2.0.1
  test: ^1.22.2

dependency_overrides:
  ngast:
    path: ../ngast
  ngcompiler:
    path: ../ngcompiler
  ngdart:
    path: ../ngdart
