# Created with package:mono_repo v6.3.0
name: Dart CI

on:
  push:
    branches:
      - master
      - google
  pull_request:
    branches:
      - master
      - google

defaults:
  run:
    shell: bash

env:
  PUB_ENVIRONMENT: bot.github

permissions: read-all

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: dart-lang/setup-dart@v1.4
      - name: Checkout
        uses: actions/checkout@v3
      - name: Activate
        run: dart pub global activate melos
      - name: Bootstrap
        run: dart pub global run melos bootstrap
      - name: Analyze
        run: dart pub global run melos run analyze
      - name: Build
        run: dart pub global run melos run build
      - name: Build
        run: dart pub global run melos run build
      - name: Test VM
        run: dart pub global run melos run test_vm
      - name: Test WEB
        run: dart pub global run melos run test_web
